spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://ep-delicate-mud-a2dobrcu-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_MbqFT5t6WlcH
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

 spring.flyway.enabled=false
AWS_S3_BUCKET = mon-bucket-local
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
aws.eventBridge.bus=local-dummy-bus